package com.guness.kiosk.ws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.10.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class SCACardServiceResponse extends SCAApiResponse implements KvmSerializable
{

    
    public SCABankData Bank;
    
    public SCACardData Card;
    
    public SCACustomerData Customer;
    

    public SCACardServiceResponse ()
    {
    }

    public SCACardServiceResponse (Object paramObj,SCAExtendedSoapSerializationEnvelope __envelope)
    {
	    super(paramObj, __envelope);
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
	    

        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("Bank"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Bank = (SCABankData)__envelope.get(j,SCABankData.class,false);
                    }
                    continue;
                }
                if (info.name.equals("Card"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Card = (SCACardData)__envelope.get(j,SCACardData.class,false);
                    }
                    continue;
                }
                if (info.name.equals("Customer"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.Customer = (SCACustomerData)__envelope.get(j,SCACustomerData.class,false);
                    }
                    continue;
                }

            }

        }



    }
    
    

    @Override
    public Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return this.Bank!=null?this.Bank:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return this.Card!=null?this.Card:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return this.Customer!=null?this.Customer:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = SCABankData.class;
            info.name = "Bank";
            info.namespace= "http://schemas.datacontract.org/2004/07/F2M.Api.Soap.CardService.Contracts.Response.Card";
        }
        if(propertyIndex==count+1)
        {
            info.type = SCACardData.class;
            info.name = "Card";
            info.namespace= "http://schemas.datacontract.org/2004/07/F2M.Api.Soap.CardService.Contracts.Response.Card";
        }
        if(propertyIndex==count+2)
        {
            info.type = SCACustomerData.class;
            info.name = "Customer";
            info.namespace= "http://schemas.datacontract.org/2004/07/F2M.Api.Soap.CardService.Contracts.Response.Card";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

